<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'DoctrineORMModule\Module'                                        => __DIR__ . '/Module.php',
    'DoctrineORMModule\Authentication\Adapter\DoctrineDocument'       => __DIR__ . '/src/DoctrineORMModule/Authentication/Adapter/DoctrineEntity.php',
    'DoctrineORMModule\Doctrine\ORM\Configuration'                    => __DIR__ . '/src/DoctrineORMModule/Doctrine/ORM/Configuration.php',
    'DoctrineORMModule\Doctrine\ORM\Connection'                       => __DIR__ . '/src/DoctrineORMModule/Doctrine/ORM/Connection.php',
    'DoctrineORMModule\Doctrine\ORM\DriverChain'                      => __DIR__ . '/src/DoctrineORMModule/Doctrine/ORM/DriverChain.php',
    'DoctrineORMModule\Factory\Connection'                            => __DIR__ . '/src/DoctrineORMModule/Factory/Connection.php',
    'DoctrineORMModule\Factory\EntityManager'                         => __DIR__ . '/src/DoctrineORMModule/Factory/EntityManager.php',
    'DoctrineORMModule\Paginator\Adapter'                             => __DIR__ . '/src/DoctrineORMModule/Paginator/Adapter.php',
    'DoctrineORMModuleTest\Assets\Entity\Test'                        => __DIR__ . '/tests/DoctrineORMModuleTest/Assets/Entity/Test.php',
    'DoctrineORMModuleTest\Authentication\Adapter\DoctrineEntityTest' => __DIR__ . '/tests/DoctrineORMModuleTest/Authentication/Adapter/DoctrineEntityTest.php',
    'DoctrineORMModuleTest\Di\ConnectionTest'                         => __DIR__ . '/tests/DoctrineORMModuleTest/Di/ConnectionTest.php',
    'DoctrineORMModuleTest\Di\EntityManagerTest'                      => __DIR__ . '/tests/DoctrineORMModuleTest/Di/EntityManagerTest.php',
    'DoctrineORMModuleTest\Doctrine\CliTest'                          => __DIR__ . '/tests/DoctrineORMModuleTest/Doctrine/CliTest.php',
    'DoctrineORMModuleTest\Framework\TestCase'                        => __DIR__ . '/tests/DoctrineORMModuleTest/Framework/TestCase.php',
);