name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - ".github/workflows/continuous-integration.yml"
      - "composer.*"
      - "src/**"
      - "phpunit.xml.dist"
      - "tests/**"
  push:
    branches:
      - "*.x"
    paths:
      - ".github/workflows/continuous-integration.yml"
      - "composer.*"
      - "src/**"
      - "phpunit.xml.dist"
      - "tests/**"

jobs:
  phpunit:
    name: "PHPUnit"
    runs-on: "ubuntu-20.04"

    strategy:
      fail-fast: false
      matrix:
        php-version:
          - "8.1"
          - "8.2"
          - "8.3"
        dbal-version:
          - "3.3.0"
        dependencies:
          - "highest"
        optional-dependencies:
          - true
          - false
        include:
          - php-version: "8.1"
            dbal-version: "3.3.0"
            dependencies: "lowest"
            optional-dependencies: false
          - php-version: "8.1"
            dbal-version: "3.3.0"
            dependencies: "lowest"
            optional-dependencies: true

    services:
      mysql:
        image: "mysql:8.0"

        options: >-
          --health-cmd "mysqladmin ping --silent"
          -e MYSQL_ALLOW_EMPTY_PASSWORD=yes
          -e MYSQL_DATABASE=database

        ports:
          - "3306:3306"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2

      - name: "Install PHP with PCOV"
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php-version }}"
          coverage: "pcov"
          ini-values: "zend.assertions=1"
          extensions: "pdo_mysql"

      - name: "Set COMPOSER_ROOT_VERSION"
        run: |
          echo "COMPOSER_ROOT_VERSION=${{ inputs.composer-root-version }}" >> $GITHUB_ENV
        if: "${{ inputs.composer-root-version }}"

      - name: "Require specific DBAL version"
        run: "composer require doctrine/dbal ^${{ matrix.dbal-version }} --no-update"

      - name: "Install dependencies with Composer"
        uses: "ramsey/composer-install@v3"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "${{ inputs.composer-options }}"

      - name: "Remove optional dependencies"
        if: "! matrix.optional-dependencies"
        run: "composer remove --dev doctrine/data-fixtures doctrine/migrations"

      - name: "Configure test application"
        run: "cp ci/config/application.config.php config/application.config.php"

      - name: "Create cache directory"
        run: "mkdir -p data/DoctrineModule/cache"

      - name: "Run PHPUnit"
        run: "vendor/bin/phpunit --coverage-clover=coverage.xml"

      - name: "Run CLI commands"
        run: "./ci/run-cli.sh"

      - name: "Run migration CLI commands"
        if: "${{ matrix.optional-dependencies }}"
        run: "./ci/run-cli-migrations.sh"

      - name: "Upload coverage file"
        uses: "actions/upload-artifact@v4"
        with:
          name: "phpunit-${{ matrix.php-version }}-${{ matrix.dependencies }}-${{ matrix.optional-dependencies }}-${{ matrix.dbal-version }}.coverage"
          path: "coverage.xml"

  upload_coverage:
    name: "Upload coverage to Codecov"
    runs-on: "ubuntu-22.04"
    needs:
      - "phpunit"

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v4"
        with:
          fetch-depth: 2

      - name: "Download coverage files"
        uses: "actions/download-artifact@v4"
        with:
          path: "reports"

      - name: "Upload to Codecov"
        uses: "codecov/codecov-action@v5"
        with:
          directory: "reports"
        env:
          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
